### ISSUE TITLE
Add Notes

### ISSUE THREAD

**Issue by unitiweb** [unitiweb/stack-commander#1]
Add the ability to have text display on the console after a complicated command runs.

An example might be the `stack init` command. When it completes a note could show on the console to update the values in the `.env` file.

Config might look something like this:

```
stack:
  commands:
    init:
      description: Some description
      completed: Now update the .env file with your values
      commands:
        - command one
        - command two
```

Or, completed could have multiple lines by adding as an array

```
stack:
  commands:
    init:
      description: Some description
      completed: 
        - Completed line one
        - Completed line two
      commands:
        - command one
        - command two
```
