### ISSUE TITLE
Add Output Options to Commands

### ISSUE THREAD

**Issue by unitiweb** [unitiweb/stack-commander#2]
It might be cool to be able to have some output options that can be used in commands

Example:

```
stack:
    commands:
        up:
            commands:
                - echo "I am running my first command"
                - ${__OUTPUT_LINE__}
                - ${__OUTPUT_TEXT('some text here')__}
                - echo "I am running my second command"
```

This should output something like this:

```
I am running my first command
-------------------------------------------------
-- some text here (this will be formatted in a certain way)
I am running my second command
```
