### ISSUE TITLE
Description with multiple lines

### ISSUE THREAD

**Issue by unitiweb** [unitiweb/stack-commander#4]
Allow the description field to be an array so the command description can have multiple lines.

```
stack:
    commands:
        up:
            description:
                - This is line one
                - This is line two
            commands: echo "Do Something Here"
```

**Comment by unitiweb** [comment]
Instead of having an array of description lines like above it turns out you can already do this with yaml by simply doing this:

```
stack:
    commands:
        up:
            description: |
                This is line one
                This is line two
            commands: echo "Do Something Here"
```

Therefor, this issue can be closed when the documentation is updated to reflect this.
