### ISSUE TITLE
Add working directory

### ISSUE THREAD

**Issue by unitiweb** [unitiweb/stack-commander#8]
Add the ability to set the working directory that the commands should be ran in.

Examle:

```
stack:
  commands:
      latest:
        name: Tag app to the latest tag
        directory: ub-web
        commands:
          - command 1
          - command 2
          - etc...
```
